// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC9JbqoTDESsF8c7wHmu5bkN2POrKNsX4',
    appId: '1:57933833507:web:60423e016393e079d51896',
    messagingSenderId: '57933833507',
    projectId: 'helium-chat-6d522',
    authDomain: 'helium-chat-6d522.firebaseapp.com',
    storageBucket: 'helium-chat-6d522.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzR3hcZR5TplQN_i9psi6_eYwI16rCXkc',
    appId: '1:57933833507:android:1807966d564988eed51896',
    messagingSenderId: '57933833507',
    projectId: 'helium-chat-6d522',
    storageBucket: 'helium-chat-6d522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXIxuWRpV_ieu269OXw3hBH958lk0d-Z4',
    appId: '1:57933833507:ios:77b5608b856c7d92d51896',
    messagingSenderId: '57933833507',
    projectId: 'helium-chat-6d522',
    storageBucket: 'helium-chat-6d522.appspot.com',
    iosClientId: '57933833507-k00tadc2dgiannt2po9nc38jdugvoe8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.heliumChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXIxuWRpV_ieu269OXw3hBH958lk0d-Z4',
    appId: '1:57933833507:ios:2f164913fef16c06d51896',
    messagingSenderId: '57933833507',
    projectId: 'helium-chat-6d522',
    storageBucket: 'helium-chat-6d522.appspot.com',
    iosClientId: '57933833507-or8h9f4lkpl2tq07msusrhid1fv3jevh.apps.googleusercontent.com',
    iosBundleId: 'com.example.heliumChatApplication.RunnerTests',
  );
}
